name: my first cicd

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        
      - name: Run test
        run: npm test
    

