name: my first cicd

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Run test
        run: npm test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          path: /temp/.build-cache
          key: ${{runner.os}}-buildx-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-buildx-

      - name: Login to githu container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
          

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.5.0
        with:
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: temp-image

    

